# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180126_1720'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suitechangelog',
            table='suite_change_log',
        ),
    ]
