# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('project_desc', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('project_title', models.CharField(max_length=20, verbose_name='\u9879\u76ee\u7b80\u79f0')),
                ('project_root', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u6839\u76ee\u5f55')),
                ('project_status', models.BooleanField(default=True, verbose_name='\u9879\u76ee\u72b6\u6001')),
                ('project_key', models.CharField(max_length=20, verbose_name='\u9879\u76eekey')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.IntegerField(verbose_name='\u914d\u7f6e\u7c7b\u578b')),
                ('setting_value', models.TextField(max_length=500, verbose_name='\u914d\u7f6e\u503c')),
                ('setting_desc', models.TextField(max_length=500, verbose_name='\u914d\u7f6e\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='project.Projects')),
            ],
            options={
                'db_table': 'project_settings',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('start_time', models.DateTimeField(null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('stop_time', models.DateTimeField(null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='project.Projects')),
            ],
            options={
                'db_table': 'test_task',
            },
        ),
    ]
